# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4.xci
# IP: The module: 'mcu_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mcu_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mcu_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mcu_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4.xci
# IP: The module: 'mcu_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mcu_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mcu_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/smk62/Documents/vivado/Final/Final.srcs/sources_1/bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mcu_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
