# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Lab_5.xdc

# Block Designs: bd/mcu/mcu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu || ORIG_REF_NAME==mcu} -quiet] -quiet

# IP: bd/mcu/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mcu/ip/mcu_axi_gpio_0_4/mcu_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_4 || ORIG_REF_NAME==mcu_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mcu/ip/mcu_axi_gpio_0_5/mcu_axi_gpio_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_5 || ORIG_REF_NAME==mcu_axi_gpio_0_5} -quiet] -quiet

# IP: bd/mcu/ip/mcu_processing_system7_0_1/mcu_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_processing_system7_0_1 || ORIG_REF_NAME==mcu_processing_system7_0_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_ps7_0_axi_periph_1/mcu_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_ps7_0_axi_periph_1 || ORIG_REF_NAME==mcu_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_rst_ps7_0_50M_1/mcu_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_rst_ps7_0_50M_1 || ORIG_REF_NAME==mcu_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_xbar_1/mcu_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_xbar_1 || ORIG_REF_NAME==mcu_xbar_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_axi_bram_ctrl_0_0/mcu_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mcu_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mcu/ip/mcu_blk_mem_gen_0_1/mcu_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_blk_mem_gen_0_1 || ORIG_REF_NAME==mcu_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_hash_0_0/mcu_hash_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_hash_0_0 || ORIG_REF_NAME==mcu_hash_0_0} -quiet] -quiet

# IP: bd/mcu/ip/mcu_axi_gpio_0_1/mcu_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_1 || ORIG_REF_NAME==mcu_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_axi_gpio_0_2/mcu_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_2 || ORIG_REF_NAME==mcu_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mcu/ip/mcu_auto_pc_4/mcu_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_4 || ORIG_REF_NAME==mcu_auto_pc_4} -quiet] -quiet

# IP: bd/mcu/ip/mcu_auto_pc_3/mcu_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_3 || ORIG_REF_NAME==mcu_auto_pc_3} -quiet] -quiet

# IP: bd/mcu/ip/mcu_auto_pc_2/mcu_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_2 || ORIG_REF_NAME==mcu_auto_pc_2} -quiet] -quiet

# IP: bd/mcu/ip/mcu_auto_pc_1/mcu_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_1 || ORIG_REF_NAME==mcu_auto_pc_1} -quiet] -quiet

# IP: bd/mcu/ip/mcu_auto_pc_0/mcu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_0 || ORIG_REF_NAME==mcu_auto_pc_0} -quiet] -quiet

# IP: bd/mcu/ip/mcu_auto_pc_5/mcu_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_5 || ORIG_REF_NAME==mcu_auto_pc_5} -quiet] -quiet

# XDC: bd/mcu/mcu_ooc.xdc
